version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - _env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: _env
    depends_on:
      - database
#    networks:
#      - default
    expose:
      - "6504"
volumes:
  data: